# Generated by Django 3.1.4 on 2021-01-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('U_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(default='', max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.IntegerField()),
                ('ADDR', models.CharField(default='', max_length=500)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
