# Generated by Django 3.1.4 on 2021-01-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='EMAIL',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='PHONE',
            field=models.IntegerField(default=''),
        ),
    ]
